[package]
name = "ziren-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
zkm-sdk = { git = "https://github.com/ProjectZKM/Ziren.git", tag = "v1.2.4" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
sha2 = "0.9"

[lib]
crate-type = ["staticlib"]
name = "ziren_glue"
