[package]
name = "hashsig-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
ream-post-quantum-crypto = { git = "https://github.com/ReamLabs/ream", package = "ream-post-quantum-crypto", rev = "005abb67fbe29ff47b1c246e10f8be86f1cb1c74" }
hashsig = { git = "https://github.com/b-wagn/hash-sig", rev = "9f2b0bbaa9deee3d072122b32c39b8027c3fccd8" }
bincode = { version = "2.0", features = ["serde"] }
sha2 = "0.10"
rand = "0.9.2"
rand_chacha = "0.9.0"

[lib]
crate-type = ["staticlib"]
name = "hashsig_glue"
